# Generated by Django 4.0.1 on 2022-01-13 08:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Choice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('choice_text', models.CharField(max_length=200)),
                ('votes', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Ques',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ques_text', models.CharField(max_length=200)),
                ('pub_date', models.DateTimeField(verbose_name='date pub')),
            ],
        ),
        migrations.DeleteModel(
            name='Artic',
        ),
        migrations.DeleteModel(
            name='Rep',
        ),
        migrations.AddField(
            model_name='choice',
            name='ques',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.ques'),
        ),
    ]
